package uml.hotel.view;

import java.util.List;

import uml.hotel.model.CheckInDAO;
import uml.hotel.model.Room;
import uml.hotel.model.RoomDAO;
import uml.hotel.model.ServiceDAO;
import uml.hotel.model.WalkInDAO;

import javax.swing.ImageIcon;
import javax.swing.JButton;

import java.awt.Color;
import java.awt.Font;

/*
 * hotel.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class hotel extends javax.swing.JFrame {

	/** Creates new form hotel */
	public hotel() {
		initComponents();
		RoomDAO rd = new RoomDAO();
		List r = rd.findAll();
		String all = Integer.toString(r.size());
		jLabel6.setText(all); //ËùÓÐ·¿¼äÊýÁ¿

		CheckInDAO cd = new CheckInDAO();
		List C = cd.findAll();
		String Call = Integer.toString(C.size());
		jLabel7.setText(Call); //ËùÓÐÔ¤¶©Èë×¡·¿¼äÊýÁ¿

		WalkInDAO wd = new WalkInDAO();
		List W = wd.findAll();
		String Wall = Integer.toString(W.size());
		jLabel8.setText(Wall); //ËùÓÐÉ¢¿ÍÈë×¡·¿¼äÊýÁ¿

		ServiceDAO s = new ServiceDAO();
		List S = s.findAll();
		String sall = Integer.toString(S.size());
		jLabel9.setText(sall); //ËùÓÐÉ¢¿ÍÈë×¡·¿¼äÊýÁ¿
		
		reflash(jButton6);
		reflash(jButton7);
		reflash(jButton8);
		reflash(jButton9);
		reflash(jButton10);
		reflash(jButton11);
		reflash(jButton12);
		reflash(jButton13);
		reflash(jButton14);
		reflash(jButton18);
		reflash(jButton19);
		reflash(jButton20);
		reflash(jButton21);
		reflash(jButton22);
		reflash(jButton23);
		reflash(jButton24);
		reflash(jButton25);
		reflash(jButton26);
		reflash(jButton27);
		reflash(jButton28);
		reflash(jButton29);
		reflash(jButton30);
		reflash(jButton31);
		reflash(jButton32);
		reflash(jButton33);
		reflash(jButton34);
		reflash(jButton40);
		reflash(jButton41);
		reflash(jButton42);
		reflash(jButton43);
		reflash(jButton46);
		reflash(jButton47);
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jButton15 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jTabbedPane8 = new javax.swing.JTabbedPane();
		jTabbedPane8.setFont(new Font("Î¢ÈíÑÅºÚ", Font.PLAIN, 15));
		jPanel9 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton16 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jLayeredPane2 = new javax.swing.JLayeredPane();
		jButton18 = new javax.swing.JButton();
		jButton18.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton19 = new javax.swing.JButton();
		jButton19.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton20 = new javax.swing.JButton();
		jButton20.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton21 = new javax.swing.JButton();
		jButton21.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton22 = new javax.swing.JButton();
		jButton22.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton23 = new javax.swing.JButton();
		jButton23.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton24 = new javax.swing.JButton();
		jButton24.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton25 = new javax.swing.JButton();
		jButton25.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton26 = new javax.swing.JButton();
		jButton26.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jLabel10 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLayeredPane5 = new javax.swing.JLayeredPane();
		jButton31 = new javax.swing.JButton();
		jButton31.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton32 = new javax.swing.JButton();
		jButton32.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton33 = new javax.swing.JButton();
		jButton33.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton34 = new javax.swing.JButton();
		jButton34.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jLabel13 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jLayeredPane6 = new javax.swing.JLayeredPane();
		jButton40 = new javax.swing.JButton();
		jButton40.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton41 = new javax.swing.JButton();
		jButton41.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton42 = new javax.swing.JButton();
		jButton42.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton43 = new javax.swing.JButton();
		jButton43.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jLabel14 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLayeredPane7 = new javax.swing.JLayeredPane();
		jButton47 = new javax.swing.JButton();
		jButton47.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 20));
		jButton46 = new javax.swing.JButton();
		jButton46.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 20));
		jLabel15 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("\u5bbe\u9986\u7ba1\u7406\u7cfb\u7edf");
		setResizable(false);

		jButton15.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/7.gif"))); // NOI18N
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});
		jButton15.setBounds(593, 25, 88, 40);
		jLayeredPane1.add(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/22.gif"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(26, 25, 80, 40);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel2.setText("\u603b\u623f\u95f4\u6570\uff1a");

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel3.setText("\u9884\u8ba2\u623f\u95f4\uff1a");

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel4.setText("\u6563\u5ba2\u623f\u95f4\uff1a");

		jLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel5.setText("\u5546\u54c1\u603b\u6570\uff1a");

		jButton16.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton16.setText("\u5237\u65b0");
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jLabel6.setForeground(new java.awt.Color(255, 0, 0));

		jLabel7.setForeground(new java.awt.Color(255, 0, 0));

		jLabel8.setForeground(new java.awt.Color(255, 0, 0));

		jLabel9.setForeground(new java.awt.Color(255, 0, 0));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				57,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				57,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				12,
																				12,
																				12)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				57,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel9,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				57,
																				Short.MAX_VALUE)))
										.addGap(24, 24, 24)).addGroup(
								jPanel9Layout.createSequentialGroup().addGap(
										51, 51, 51).addComponent(jButton16)
										.addContainerGap(63, Short.MAX_VALUE)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addGap(42, 42, 42)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(29, 29, 29)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(57, 57, 57).addComponent(
												jButton16).addContainerGap(68,
												Short.MAX_VALUE)));

		jTabbedPane8.addTab("\u5bbe\u9986\u4fe1\u606f", jPanel9);

		jTabbedPane8.setBounds(10, 90, 180, 370);
		jLayeredPane1.add(jTabbedPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton2.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/4.gif"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(132, 25, 90, 40);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton3.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/5.gif"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.setBounds(248, 25, 85, 40);
		jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton4.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/6.gif"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jButton4.setBounds(359, 25, 85, 40);
		jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton5.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/8.gif"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jButton5.setBounds(470, 25, 97, 40);
		jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton18.setText("BS001");
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});
		jButton18.setBounds(60, 54, 86, 40);
		jLayeredPane2.add(jButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton19.setText("BS002");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});
		jButton19.setBounds(206, 54, 86, 40);
		jLayeredPane2.add(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton20.setText("BS003");
		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});
		jButton20.setBounds(352, 54, 93, 40);
		jLayeredPane2.add(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton21.setText("BS004");
		jButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton21ActionPerformed(evt);
			}
		});
		jButton21.setBounds(60, 148, 86, 40);
		jLayeredPane2.add(jButton21, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton22.setText("BS005");
		jButton22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton22ActionPerformed(evt);
			}
		});
		jButton22.setBounds(206, 148, 86, 40);
		jLayeredPane2.add(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton23.setText("BS006");
		jButton23.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton23ActionPerformed(evt);
			}
		});
		jButton23.setBounds(352, 148, 93, 40);
		jLayeredPane2.add(jButton23, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton24.setText("BS007");
		jButton24.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton24ActionPerformed(evt);
			}
		});
		jButton24.setBounds(60, 242, 86, 40);
		jLayeredPane2.add(jButton24, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton25.setText("BS008");
		jButton25.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton25ActionPerformed(evt);
			}
		});
		jButton25.setBounds(206, 242, 86, 40);
		jLayeredPane2.add(jButton25, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton26.setText("BS009");
		jButton26.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton26ActionPerformed(evt);
			}
		});
		jPanel2 = new javax.swing.JPanel();
		jLayeredPane3 = new javax.swing.JLayeredPane();
		jButton6 = new javax.swing.JButton();
		jButton6.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton7 = new javax.swing.JButton();
		jButton7.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton8 = new javax.swing.JButton();
		jButton8.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton9 = new javax.swing.JButton();
		jButton9.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton10 = new javax.swing.JButton();
		jButton10.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton11 = new javax.swing.JButton();
		jButton11.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton12 = new javax.swing.JButton();
		jButton12.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton13 = new javax.swing.JButton();
		jButton13.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jButton14 = new javax.swing.JButton();
		jButton14.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 15));
		jLabel11 = new javax.swing.JLabel();
		
				jButton6.setText("BD001");
				jButton6.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton6ActionPerformed(evt);
					}
				});
				jButton6.setBounds(61, 55, 86, 40);
				jLayeredPane3.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
				
						jButton7.setText("BD002");
						jButton7.addActionListener(new java.awt.event.ActionListener() {
							public void actionPerformed(java.awt.event.ActionEvent evt) {
								jButton7ActionPerformed(evt);
							}
						});
						jButton7.setBounds(208, 55, 86, 40);
						jLayeredPane3.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
						
								jButton8.setText("BD003");
								jButton8.addActionListener(new java.awt.event.ActionListener() {
									public void actionPerformed(java.awt.event.ActionEvent evt) {
										jButton8ActionPerformed(evt);
									}
								});
								jButton8.setBounds(355, 55, 86, 40);
								jLayeredPane3.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
								
										jButton9.setText("BD004");
										jButton9.addActionListener(new java.awt.event.ActionListener() {
											public void actionPerformed(java.awt.event.ActionEvent evt) {
												jButton9ActionPerformed(evt);
											}
										});
										jButton9.setBounds(61, 150, 86, 40);
										jLayeredPane3.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
										
												jButton10.setText("BD005");
												jButton10.addActionListener(new java.awt.event.ActionListener() {
													public void actionPerformed(java.awt.event.ActionEvent evt) {
														jButton10ActionPerformed(evt);
													}
												});
												jButton10.setBounds(208, 150, 86, 40);
												jLayeredPane3.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
												
														jButton11.setText("BD006");
														jButton11.addActionListener(new java.awt.event.ActionListener() {
															public void actionPerformed(java.awt.event.ActionEvent evt) {
																jButton11ActionPerformed(evt);
															}
														});
														jButton11.setBounds(355, 150, 86, 40);
														jLayeredPane3.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
														
																jButton12.setText("BD007");
																jButton12.addActionListener(new java.awt.event.ActionListener() {
																	public void actionPerformed(java.awt.event.ActionEvent evt) {
																		jButton12ActionPerformed(evt);
																	}
																});
																jButton12.setBounds(61, 245, 86, 40);
																jLayeredPane3.add(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
																
																		jButton13.setText("BD008");
																		jButton13.addActionListener(new java.awt.event.ActionListener() {
																			public void actionPerformed(java.awt.event.ActionEvent evt) {
																				jButton13ActionPerformed(evt);
																			}
																		});
																		jButton13.setBounds(208, 245, 86, 40);
																		jLayeredPane3.add(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
																		
																				jButton14.setText("BD009");
																				jButton14.addActionListener(new java.awt.event.ActionListener() {
																					public void actionPerformed(java.awt.event.ActionEvent evt) {
																						jButton14ActionPerformed(evt);
																					}
																				});
																				jButton14.setBounds(355, 245, 86, 40);
																				jLayeredPane3.add(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);
																				
																						jLabel11.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/biaodan.jpg")));
																						jLabel11.setBounds(0, 0, 500, 340);
																						jLayeredPane3.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
																						
																								javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
																										jPanel2);
																								jPanel2.setLayout(jPanel2Layout);
																								jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																										jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
																										Short.MAX_VALUE));
																								jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING).addGroup(
																										jPanel2Layout.createSequentialGroup().addComponent(
																												jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
																												343, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)));
																								
																										jTabbedPane1.addTab("\u6807\u51c6\u5355\u4eba\u95f4", jPanel2);
		jButton26.setBounds(352, 242, 93, 40);
		jLayeredPane2.add(jButton26, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel10.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/biaoshuang.jpg")));
		jLabel10.setBounds(0, 0, 510, 340);
		jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addComponent(
						jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
						337, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u6807\u51c6\u53cc\u4eba\u95f4", jPanel3);

		jButton31.setText("HS001");
		jButton31.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton31ActionPerformed(evt);
			}
		});
		jButton31.setBounds(106, 76, 93, 54);
		jLayeredPane5.add(jButton31, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton32.setText("HS002");
		jButton32.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton32ActionPerformed(evt);
			}
		});
		jButton32.setBounds(305, 76, 93, 54);
		jLayeredPane5.add(jButton32, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton33.setText("HS003");
		jButton33.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton33ActionPerformed(evt);
			}
		});
		jButton33.setBounds(106, 206, 93, 54);
		jLayeredPane5.add(jButton33, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton34.setText("HS004");
		jButton34.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton34ActionPerformed(evt);
			}
		});
		jPanel4 = new javax.swing.JPanel();
		jLayeredPane4 = new javax.swing.JLayeredPane();
		jButton30 = new javax.swing.JButton();
		jButton30.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton29 = new javax.swing.JButton();
		jButton29.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton28 = new javax.swing.JButton();
		jButton28.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jButton27 = new javax.swing.JButton();
		jButton27.setFont(new Font("Î¢ÈíÑÅºÚ", Font.BOLD, 17));
		jLabel12 = new javax.swing.JLabel();
		
				jButton30.setText("HD004");
				jButton30.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton30ActionPerformed(evt);
					}
				});
				jButton30.setBounds(305, 206, 93, 54);
				jLayeredPane4.add(jButton30, javax.swing.JLayeredPane.DEFAULT_LAYER);
				
						jButton29.setText("HD003");
						jButton29.addActionListener(new java.awt.event.ActionListener() {
							public void actionPerformed(java.awt.event.ActionEvent evt) {
								jButton29ActionPerformed(evt);
							}
						});
						jButton29.setBounds(106, 206, 93, 54);
						jLayeredPane4.add(jButton29, javax.swing.JLayeredPane.DEFAULT_LAYER);
						
								jButton28.setText("HD002");
								jButton28.addActionListener(new java.awt.event.ActionListener() {
									public void actionPerformed(java.awt.event.ActionEvent evt) {
										jButton28ActionPerformed(evt);
									}
								});
								jButton28.setBounds(305, 76, 93, 54);
								jLayeredPane4.add(jButton28, javax.swing.JLayeredPane.DEFAULT_LAYER);
								
										jButton27.setText("HD001");
										jButton27.addActionListener(new java.awt.event.ActionListener() {
											public void actionPerformed(java.awt.event.ActionEvent evt) {
												jButton27ActionPerformed(evt);
											}
										});
										jButton27.setBounds(106, 76, 93, 54);
										jLayeredPane4.add(jButton27, javax.swing.JLayeredPane.DEFAULT_LAYER);
										
												jLabel12.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/haodan .jpg")));
												jLabel12.setBounds(0, 0, 510, 340);
												jLayeredPane4.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
												
														javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
																jPanel4);
														jPanel4.setLayout(jPanel4Layout);
														jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
																Short.MAX_VALUE));
														jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 339,
																Short.MAX_VALUE));
														
																jTabbedPane1.addTab("\u8c6a\u534e\u5355\u4eba\u95f4", jPanel4);
		jButton34.setBounds(305, 206, 93, 54);
		jLayeredPane5.add(jButton34, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel13.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/haoshuang.jpg"))); // NOI18N
		jLabel13.setBounds(0, 0, 510, 340);
		jLayeredPane5.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 339,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("\u8c6a\u534e\u53cc\u4eba\u95f4", jPanel5);

		jButton40.setText("SW001");
		jButton40.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton40ActionPerformed(evt);
			}
		});
		jButton40.setBounds(106, 77, 93, 54);
		jLayeredPane6.add(jButton40, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton41.setText("SW002");
		jButton41.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton41ActionPerformed(evt);
			}
		});
		jButton41.setBounds(305, 77, 93, 54);
		jLayeredPane6.add(jButton41, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton42.setText("SW003");
		jButton42.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton42ActionPerformed(evt);
			}
		});
		jButton42.setBounds(106, 208, 93, 54);
		jLayeredPane6.add(jButton42, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton43.setText("SW004");
		jButton43.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton43ActionPerformed(evt);
			}
		});
		jButton43.setBounds(305, 208, 93, 54);
		jLayeredPane6.add(jButton43, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel14.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/taofang.jpg")));
		jLabel14.setBounds(0, 0, 510, 340);
		jLayeredPane6.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
				Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel6Layout.createSequentialGroup().addComponent(
						jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE,
						339, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
						261, 261, 261)));

		jTabbedPane1.addTab("\u5546\u52a1\u5957\u623f", jPanel6);

		jButton47.setText("ZT002");
		jButton47.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton47ActionPerformed(evt);
			}
		});
		jButton47.setBounds(296, 124, 120, 76);
		jLayeredPane7.add(jButton47, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton46.setText("ZT001");
		jButton46.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton46ActionPerformed(evt);
			}
		});
		jButton46.setBounds(88, 124, 120, 76);
		jLayeredPane7.add(jButton46, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel15.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/zongtong.jpg")));
		jLabel15.setBounds(0, 0, 510, 340);
		jLayeredPane7.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
				Short.MAX_VALUE));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 339,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("\u603b\u7edf\u5957\u623f", jPanel7);

		jTabbedPane1.setBounds(190, 90, 510, 370);
		jLayeredPane1.add(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel1
				.setIcon(new ImageIcon(hotel.class.getResource("/uml/hotel/view/meigong/6300737_153725053964_2.jpg")));
		jLabel1.setBounds(0, 0, 720, 480);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
						467, Short.MAX_VALUE).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	
	//½çÃæË¢ÐÂ
	public void reflash(JButton room_id) {
		String room_idT = room_id.getText();
		WalkInDAO wd = new WalkInDAO();
		CheckInDAO CI = new CheckInDAO();
		List a1 = wd.findByRoomId(room_idT);
		List a2 = CI.findByRoomId(room_idT);

		if ((a1.size() == 0) && (a2.size() == 0)) {
			room_id.setForeground(Color.green);
		} else{
			room_id.setForeground(Color.red);
		}
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RoomDAO rd = new RoomDAO();
		List r = rd.findAll();
		String all = Integer.toString(r.size());
		jLabel6.setText(all); //ËùÓÐ·¿¼äÊýÁ¿

		CheckInDAO cd = new CheckInDAO();
		List C = cd.findAll();
		String Call = Integer.toString(C.size());
		jLabel7.setText(Call); //ËùÓÐÔ¤¶©Èë×¡·¿¼äÊýÁ¿

		WalkInDAO wd = new WalkInDAO();
		List W = wd.findAll();
		String Wall = Integer.toString(W.size());
		jLabel8.setText(Wall); //ËùÓÐÉ¢¿ÍÈë×¡·¿¼äÊýÁ¿

		ServiceDAO s = new ServiceDAO();
		List S = s.findAll();
		String sall = Integer.toString(S.size());
		jLabel9.setText(sall); //ËùÓÐÉ¢¿ÍÈë×¡·¿¼äÊýÁ¿
		
		reflash(jButton6);
		reflash(jButton7);
		reflash(jButton8);
		reflash(jButton9);
		reflash(jButton10);
		reflash(jButton11);
		reflash(jButton12);
		reflash(jButton13);
		reflash(jButton14);
		reflash(jButton18);
		reflash(jButton19);
		reflash(jButton20);
		reflash(jButton21);
		reflash(jButton22);
		reflash(jButton23);
		reflash(jButton24);
		reflash(jButton25);
		reflash(jButton26);
		reflash(jButton27);
		reflash(jButton28);
		reflash(jButton29);
		reflash(jButton30);
		reflash(jButton31);
		reflash(jButton32);
		reflash(jButton33);
		reflash(jButton34);
		reflash(jButton40);
		reflash(jButton41);
		reflash(jButton42);
		reflash(jButton43);
		reflash(jButton46);
		reflash(jButton47);


	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		food f = new food();
		f.show();
	}

	private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton47.getText();
		find(room_id);
	}

	private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton46.getText();
		find(room_id);
	}

	private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton43.getText();
		find(room_id);
	}

	private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton42.getText();
		find(room_id);
	}

	private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton41.getText();
		find(room_id);
	}

	private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton40.getText();
		find(room_id);
	}

	private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton34.getText();
		find(room_id);
	}

	private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton33.getText();
		find(room_id);
	}

	private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton32.getText();
		find(room_id);
	}

	private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton31.getText();
		find(room_id);
	}

	private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton30.getText();
		find(room_id);
	}

	private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton29.getText();
		find(room_id);
	}

	private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton27.getText();
		find(room_id);
	}

	private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton26.getText();
		find(room_id);
	}

	private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton25.getText();
		find(room_id);
	}

	private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton24.getText();
		find(room_id);
	}

	private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton23.getText();
		find(room_id);
	}

	private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton22.getText();
		find(room_id);
	}

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton21.getText();
		find(room_id);
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton20.getText();
		find(room_id);
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton19.getText();
		find(room_id);
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton18.getText();
		find(room_id);
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton14.getText();
		find(room_id);
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton13.getText();
		find(room_id);
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton12.getText();
		find(room_id);
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton11.getText();
		find(room_id);
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton10.getText();
		find(room_id);
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton9.getText();
		find(room_id);
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton8.getText();
		find(room_id);
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton7.getText();
		find(room_id);
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		check_in c = new check_in();
		c.show();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		servation s = new servation();
		s.show();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		UIcheckOut u = new UIcheckOut();
		u.show();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Walk w = new Walk();
		w.show();

	}

	private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton28.getText();
		find(room_id);
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jButton6.getText();
		find(room_id);

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		UIservice u = new UIservice();
		u.show();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new hotel().setVisible(true);
			}
		});
	}

	//ÅÐ¶Ï·¿¼äµÄÐÅÏ¢½ø¶øÑ¡Ôñµ¯³ö²»Í¬»î¶¯¿ò
	public void find(String room_id) {
		walk_in wi = new walk_in();
		WalkInDAO wd = new WalkInDAO();
		CheckInDAO CI = new CheckInDAO();
		List a1 = wd.findByRoomId(room_id);
		List a2 = CI.findByRoomId(room_id);

		String type;

		if ((a1.size() == 0) && (a2.size() == 0)) {
			walk_in u = new walk_in();
			u.show();
			u.show(room_id);
		} else if (a1.size() != 0) {
			UIcheckOut ui = new UIcheckOut();
			ui.show();
			ui.show(room_id, "É¢¿Í½áÕË");
		} else {
			UIcheckOut ui = new UIcheckOut();
			ui.show();
			ui.show(room_id, "Ô¤Ô¼¹Ë¿Í½áÕË");
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton27;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton29;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton31;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton33;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton43;
	private javax.swing.JButton jButton46;
	private javax.swing.JButton jButton47;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JLayeredPane jLayeredPane2;
	private javax.swing.JLayeredPane jLayeredPane3;
	private javax.swing.JLayeredPane jLayeredPane4;
	private javax.swing.JLayeredPane jLayeredPane5;
	private javax.swing.JLayeredPane jLayeredPane6;
	private javax.swing.JLayeredPane jLayeredPane7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane8;
	// End of variables declaration//GEN-END:variables

}