/*
 * UIcheckOut.java
 *
 * Created on __DATE__, __TIME__
 */

package uml.hotel.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import uml.hotel.model.CheckIn;
import uml.hotel.model.CheckInDAO;
import uml.hotel.model.Cost;
import uml.hotel.model.CostDAO;
import uml.hotel.model.Room;
import uml.hotel.model.RoomDAO;
import uml.hotel.model.WalkIn;
import uml.hotel.model.WalkInDAO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class UIcheckOut extends javax.swing.JFrame {

	/** Creates new form UIcheckOut */
	public UIcheckOut() {
		initComponents();
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		Date curDate = new Date(System.currentTimeMillis());//获取当前时间     
		String str = formatter.format(curDate);
		jTextField13.setText(str);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jTextField14 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel10 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		jTextField13 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(java.awt.SystemColor.textHighlight);
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setText("\u5165\u4f4f\u65f6\u95f4");

		jLabel3.setText("\u79bb\u5f00\u65f6\u95f4");

		jLabel4.setText("\u7ed3\u8d26\u5355\u53f7");

		jLabel6.setText("\u623f\u95f4\u5355\u4ef7");

		jLabel7.setText("\u5bbe\u5ba2\u59d3\u540d");

		jLabel8.setText("\u5bbe\u5ba2ID");

		jLabel9.setText("\u5165\u4f4f\u5929\u6570");

		jLabel16.setText("\u4f4f\u5e97\u671f\u95f4\u623f\u8d39");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				89,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				89,
																				Short.MAX_VALUE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jLabel8))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel3))))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jTextField7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																88,
																Short.MAX_VALUE)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																88,
																Short.MAX_VALUE)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																88,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel16)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField14,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addGap(
																				28,
																				28,
																				28)
																		.addComponent(
																				jTextField8)))
										.addGap(115, 115, 115)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel9)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel16)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(jLabel8)
														.addComponent(
																jTextField7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(17, Short.MAX_VALUE)));

		jPanel1.setBounds(20, 130, 630, 120);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel2.setBackground(java.awt.SystemColor.textHighlight);
		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel11
				.setText("\u8be5\u623f\u95f4\u589e\u52a0\u670d\u52a1\u6d88\u8d39\u6e05\u5355");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		jScrollPane1.setViewportView(jTable1);

		jLabel10.setText("\u623f\u95f4\u7c7b\u578b");

		jLabel12.setText("\u603b\u6d88\u8d39\u989d");

		jLabel13.setText("\u5b9e\u6536\u91d1\u989d");

		jLabel14.setText("\u627e\u96f6");

		jLabel15.setText("\u7ed3\u8d26\u65f6\u95f4");

		jButton2.setText("\u7ed3\u8d26\uff08\u786e\u5b9a\uff09");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u5173\u95ed");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u9000\u51fa");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																304,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												29,
																												29,
																												29)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel12)
																														.addComponent(
																																jLabel10)
																														.addComponent(
																																jLabel13)
																														.addComponent(
																																jLabel15)))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												39,
																												39,
																												39)
																										.addComponent(
																												jLabel14)))
																		.addGap(
																				35,
																				35,
																				35)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField10)
																						.addComponent(
																								jTextField11)
																						.addComponent(
																								jTextField12)
																						.addComponent(
																								jTextField13)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								74,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton4)))
										.addContainerGap(117, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10))
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				260,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				23,
																				23,
																				23)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel12))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel13))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField12,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel14))
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel15))
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jButton4))
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton3)))
										.addContainerGap(56, Short.MAX_VALUE)));

		jPanel2.setBounds(20, 270, 630, 370);
		jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "散客结账", "预约顾客结账" }));
		jComboBox1.setBounds(350, 70, 100, 23);
		jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 18));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u7ed3\u8d26\u7c7b\u578b");
		jLabel5.setBounds(260, 70, 80, 24);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u7ed3\u8d26\u7684\u623f\u95f4\u53f7\uff1a");
		jLabel1.setBounds(20, 70, 130, 24);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setFont(new java.awt.Font("微软雅黑", 1, 14));
		jButton1.setText("\u663e\u793a\u6d88\u8d39\u4fe1\u606f");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(510, 70, 120, 27);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField1.setBounds(150, 70, 90, 23);
		jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel17.setIcon(new ImageIcon(UIcheckOut.class.getResource("/uml/hotel/view/meigong/\u80CC\u666F6.jpg"))); // NOI18N
		jLabel17.setBounds(0, 0, 670, 670);
		jLayeredPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel3,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		deleteInfo();
		this.dispose();
		//cost.delete(cost.findByRoomId(roomId));
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String receivemoney = jTextField11.getText();
		int remoney = Integer.parseInt(receivemoney) - totalmoney;
		jTextField12.setText(Integer.toString(remoney));
	}

	public static int Day;//记录天数 计算房费
	public static int roomcost;//记录天数 计算房费
	public static int totalmoney;

	public void show(String room_id, String type) {
		jTextField1.setText(room_id);
		jComboBox1.setSelectedItem(type);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String room_id = jTextField1.getText();
		String checkType = jComboBox1.getSelectedItem().toString();

		if (checkType.equalsIgnoreCase("预约顾客结账")) {
			CheckInDAO findInfo = new CheckInDAO();//声明在入住表单中查找顾客信息的接口对象
			CheckIn c = new CheckIn();//声明一个接受表单一行的对象
			List<?> li = findInfo.findByRoomId(room_id);
			c = (CheckIn) li.get(0);
			Day = c.getLiveDate();
			setTextFiled(c.getBookingId(), c.getCustomerId(), c.getName(), c
					.getStartTime(), c.getEndTime(), Integer.toString(c
					.getLiveDate()));

		} else if (checkType.equalsIgnoreCase("散客结账")) {
			WalkInDAO findInfo = new WalkInDAO();//声明在入住表单中查找顾客信息的接口对象
			WalkIn c = new WalkIn();//声明一个接受表单一行的对象
			List<?> li = findInfo.findByRoomId(room_id);
			c = (WalkIn) li.get(0);
			Day = c.getLiveDate();
			setTextFiled(c.getBookingId(), c.getCustomerId(), c.getName(), c
					.getStartTime(), c.getEndTime(), Integer.toString(c
					.getLiveDate()));
		} else {
			System.out.println("input a wrong infomation");
		}

		RoomDAO fr = new RoomDAO();
		room_id = jTextField1.getText();
		List<?> lr = fr.findByRoomId(room_id);
		Room r = new Room();
		r = (Room) lr.get(0);
		roomcost = r.getPrice();
		roomcost = roomcost * Day;//住店期间房间费
		String cost = Integer.toString(roomcost);
		setroomcost(cost);
		setTextroom(Integer.toString(r.getPrice()), r.getDescription());

		//显示该结账房间增加消费表内容
		CostDAO co = new CostDAO();
		//Cost cIn=new Cost();
		List<?> cli = co.findByRoomId(room_id);
		settable(cli);
		//获得结账时应收金额
		int costtotal = getServerCost(cli);
		costtotal = costtotal + roomcost;
		jTextField10.setText(Integer.toString(costtotal));
		totalmoney = costtotal;//用于结账时计算找零
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UIcheckOut().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;

	// End of variables declaration//GEN-END:variables
	public void setTextFiled(String bookingId, String customerId, String name,
			String start_time, String end_time, String livedata) {
		// TODO Auto-generated method stub

		jTextField2.setText(start_time);//入住时间
		jTextField3.setText(end_time);//离开时间
		jTextField8.setText(livedata);//入住天数
		jTextField4.setText(bookingId);//结账单号
		jTextField6.setText(name);//宾客姓名
		jTextField7.setText(customerId);//宾客ID

	}

	public void setTextroom(String price, String roomtype) {
		// TODO Auto-generated method stub
		jTextField9.setText(roomtype);
		jTextField5.setText(price);

	}

	public void setroomcost(String cost) {
		// TODO Auto-generated method stub

		jTextField14.setText(cost);

	}

	public void settable(List<?> Item) {
		// TODO Auto-generated method stub
		int numItem = Item.size();
		Object o[][] = new Object[numItem][4];
		for (int i = 0; i < numItem; i++) {
			Cost sc = (Cost) ((java.util.List<?>) Item).get(i);
			o[i][0] = sc.getServiceName();
			o[i][1] = sc.getServicePrice();
			o[i][2] = sc.getNumb();
			o[i][3] = sc.getCost();
		}
		String[] coluNames = { "消费名称", "单价", "数量", "总价格" };
		jTable1.setModel(new javax.swing.table.DefaultTableModel(o, coluNames));
	}

	public int getServerCost(List<?> Item) {
		// TODO Auto-generated method stub
		int numItem = Item.size();
		int cost = 0;
		String o[][] = new String[numItem][1];
		for (int i = 0; i < numItem; i++) {
			Cost sc = (Cost) ((java.util.List<?>) Item).get(i);
			o[i][0] = sc.getCost();
			cost = cost + Integer.parseInt(o[i][0]);

		}
		return cost;
	}

	public void deleteInfo() {
		String roomId = jTextField1.getText();
		String Ctype = jComboBox1.getSelectedItem().toString();
		//从入住表中删除顾客信息
		if (Ctype.equalsIgnoreCase("预约顾客结账")) {
			CheckInDAO findInfo = new CheckInDAO();//声明在入住表单中查找顾客信息的接口对象
			CheckIn c = new CheckIn();//声明一个接受表单一行的对象
			List<?> li = findInfo.findByRoomId(roomId);
			c = (CheckIn) li.get(0);
			findInfo.delete(c);

		} else if (Ctype.equalsIgnoreCase("散客结账")) {
			WalkInDAO findInfo = new WalkInDAO();//声明在入住表单中查找顾客信息的接口对象
			WalkIn c = new WalkIn();//声明一个接受表单一行的对象
			List<?> li = findInfo.findByRoomId(roomId);
			c = (WalkIn) li.get(0);
			findInfo.delete(c);
		} else {
			System.out.println("input a wrong infomation");
		}
		//服务表中删除增加消费的信息
		CostDAO cost = new CostDAO();
		List<?> co = cost.findByRoomId(roomId);
		int n = co.size();
		for (int i = 0; i < n; i++) {
			Cost c = (Cost) co.get(i);
			cost.delete(c);
		}
	}
}