/*
 * UIservice.java
 *
 * Created on __DATE__, __TIME__
 */

package uml.hotel.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import uml.hotel.model.Cost;
import uml.hotel.model.CostDAO;
import uml.hotel.model.Service;
import uml.hotel.model.ServiceDAO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class UIservice extends javax.swing.JFrame {

	/** Creates new form UIservice */
	public UIservice() {
		initComponents();
		ServiceDAO ser = new ServiceDAO();
		List<?> serlist = ser.findAll();
		setTableSer(serlist);
		SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd");
		Date curDate = new Date(System.currentTimeMillis());//获取当前时间     
		String str = formatter.format(curDate);
		jTextField2.setText(str);
	}

	private DefaultTableModel model1;
	private DefaultTableModel model2;

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		jButton3.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton3.setText("\u64a4\u9500");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.setBounds(560, 470, 80, 40);
		jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton2.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jButton2.setText("\u786e\u5b9a");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(400, 470, 80, 40);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel1.setBackground(java.awt.SystemColor.textHighlight);
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel2.setText("\u6d88\u8d39\u9879\u76ee\u6e05\u5355");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 18));
		jLabel3.setText("\u589e\u52a0\u670d\u52a1");

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel4.setText("\u8f93\u5165\u623f\u95f4\u53f7");

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel5.setText("\u6d88\u8d39\u5355\u53f7");

		jButton4.setText("\u6dfb\u52a0");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel6.setText("\u6d88\u8d39\u6570\u91cf");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "项目编号", "项目名称", "单价", "库存" }));
		jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		jScrollPane2.setViewportView(jTable2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																303,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel4)
																																						.addComponent(
																																								jLabel5))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								jTextField1,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								114,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								jLabel3)
																																						.addComponent(
																																								jTextField2)
																																						.addComponent(
																																								jTextField3)))
																														.addComponent(
																																jLabel2)))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel6)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				43,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton4)))
										.addGap(25, 25, 25)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(17, 17, 17)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												306, Short.MAX_VALUE)));

		jPanel1.setBounds(20, 40, 330, 490);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel2.setBackground(java.awt.SystemColor.textHighlight);
		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "消费单号", "房间号", "消费名称", "单价", "数量", "总价" }));
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 14));
		jLabel1
				.setText("\u8be5\u623f\u95f4\u589e\u52a0\u670d\u52a1\u9879\u76ee\u6e05\u5355");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel1).addGap(321, 321, 321)).addGroup(
				jPanel2Layout.createSequentialGroup().addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						289, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												325, Short.MAX_VALUE)));

		jPanel2.setBounds(370, 40, 299, 370);
		jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel7.setIcon(new ImageIcon(UIservice.class.getResource("/uml/hotel/view/meigong/\u80CC\u666F8.jpg"))); // NOI18N
		jLabel7.setBounds(-10, 0, 690, 600);
		jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addComponent(
						jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						580, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int n = model1.getRowCount();
		System.out.println(n);
		System.out.println((String) model1.getValueAt(0, 1));

		for (int i = 0; i < n; i++) {
			String roomId = (String) model1.getValueAt(i, 1);
			String serviceName = (String) model1.getValueAt(i, 2);
			String servicePrice = (String) model1.getValueAt(i, 3);
			String numb = (String) model1.getValueAt(i, 4);
			String cost = (String) model1.getValueAt(i, 5);
			Cost o = new Cost();
			CostDAO saveCost = new CostDAO();
			o.setRoomId(roomId);
			o.setServiceName(serviceName);
			o.setServicePrice(servicePrice);
			o.setNumb(numb);
			o.setCost(cost);
			saveCost.save(o);
		}

		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

		// TODO add your handling code here:
		model1 = (DefaultTableModel) this.jTable1.getModel();
		model2 = (DefaultTableModel) this.jTable2.getModel();
		String number = (String) model2.getValueAt(this.jTable2
				.getSelectedRow(), 0);
		String name = (String) model2.getValueAt(this.jTable2.getSelectedRow(),
				1);
		String perPrice = (String) model2.getValueAt(this.jTable2
				.getSelectedRow(), 2);
		//String amount = (String) model2.getValueAt(this.jTable2
		//.getSelectedRow(), 3);
		String roomid = jTextField1.getText();
		String dailnum = jTextField2.getText();
		String costnum = jTextField3.getText();
		int num = Integer.parseInt(costnum);
		num = num * Integer.parseInt(perPrice);
		String cost = Integer.toString(num);
		//int ac =Integer.parseInt(costnum);
		//int b =Integer.parseInt(perPrice); 
		//ac=ac*b;
		//String totalcost = Integer.toString(ac);
		//double amount1=Double.parseDouble(amount)-1;
		String a[] = new String[] { dailnum, roomid, name, perPrice, costnum,
				cost };
		//model1.setValueAt(Double.toString(amount1),this.jTable1.getSelectedRow()-1, 3);

		model1.addRow(a);

		//model2.removeRow(get)
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UIservice().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;

	// End of variables declaration//GEN-END:variables
	//在表中显示消费项目清单
	public void setTableSer(List<?> Item) {

		int numItem = Item.size();
		Object o[][] = new Object[numItem][4];
		for (int i = 0; i < numItem; i++) {
			Service sc = (Service) ((java.util.List<?>) Item).get(i);
			o[i][0] = sc.getSerId();
			o[i][1] = sc.getSerName();
			o[i][2] = sc.getSerPrice();
			o[i][3] = sc.getSerStcok();
		}
		String[] coluNames = { "项目编号", "项目名称", "单价", "库存" };
		jTable2.setModel(new javax.swing.table.DefaultTableModel(o, coluNames));

	}

}